# Directory containing model checkpoints.
CHECKPOINT_DIR="im2txt/model/train"

# Vocabulary file generated by the preprocessing script.
VOCAB_FILE="im2txt/data/word_counts.txt"

# JPEG image file to caption.
IMAGE_FILE="im2txt/data/Flickr8k_Dataset/667626_18933d713e.jpg"

BAZEL_PATH=~/bazel/output/bazel

# Build the inference binary.
${BAZEL_PATH} build -c opt im2txt/run_inference

# Ignore GPU devices (only necessary if your GPU is currently memory
# constrained, for example, by running the training script).
# export CUDA_VISIBLE_DEVICES=""

# Run inference to generate captions.
bazel-bin/im2txt/run_inference \
  --checkpoint_path=${CHECKPOINT_DIR} \
  --vocab_file=${VOCAB_FILE} \
  --input_files=${IMAGE_FILE}
